"""des-sim-checkin: a "State of the Board" brief for monthly strategy check-ins.

Emits a markdown brief of the measured signals and simulation context, with
deltas against the previous brief. Output goes to data/checkins/ (gitignored)
and stdout — never into the public repo or site.

BOUNDARY, by design: this module knows nothing about anyone's strategic
positions. It reports public, quantitative signals only. Interpretation —
what these readings mean for specific positions or plans — belongs in the
private document where the brief gets pasted, not in this codebase.
"""
from __future__ import annotations

import datetime as dt
import json
from pathlib import Path

import pandas as pd

from . import targets

CHECKIN_DIR = Path("data/checkins")
SUMMARY = Path("results/scenarios_summary.json")


def _pct(new: float, old: float) -> str:
    return f"{new / old - 1:+.0%}"


def gather() -> dict:
    """Collect current readings. Each is (value, context) — all public data."""
    r: dict = {"date": dt.date.today().isoformat()}

    ev = targets.design_demand_evidence()
    smoothed = ev["elasticity_evidence_ratio"].rolling(6, center=True, min_periods=1).mean()
    year_ago = smoothed.iloc[-13] if len(smoothed) > 13 else smoothed.iloc[0]
    r["evidence_ratio"] = round(float(smoothed.iloc[-1]), 2)
    r["evidence_yoy"] = _pct(smoothed.iloc[-1], year_ago)
    r["evidence_lean"] = (
        "blue (elastic-world)" if smoothed.iloc[-1] > year_ago * 1.02
        else ("red (inelastic-world)" if smoothed.iloc[-1] < year_ago * 0.98 else "neutral")
    )

    bf = targets.tech_firm_formation()
    info = bf[bf["series"] == "information_sector_applications"]
    recent = info[info["date"] >= info["date"].max() - pd.DateOffset(months=12)]["value"].mean()
    plateau = info[info["date"].dt.year.isin([2022, 2023, 2024])]["value"].mean()
    r["formation_per_month"] = round(float(recent))
    r["formation_vs_plateau"] = _pct(recent, plateau)

    lo = targets.tech_layoffs_monthly()
    vals = lo["laid_off"].iloc[:-1]
    r["layoffs_trailing_12mo_k"] = round(float(vals.iloc[-12:].sum() / 1000))
    r["layoffs_latest_month_k"] = round(float(vals.iloc[-1] / 1000), 1)

    postings = targets.design_postings_index()
    pm = postings.groupby(postings["date"].dt.to_period("M"))["postings_index"].mean()
    r["design_postings_index"] = round(float(pm.iloc[-1]), 1)
    r["design_postings_yoy"] = _pct(pm.iloc[-1], pm.iloc[-13]) if len(pm) > 13 else "n/a"

    mgmt = targets.management_postings()
    mm = mgmt.groupby(mgmt["date"].dt.to_period("M"))["postings_index"].mean()
    r["mgmt_postings_index"] = round(float(mm.iloc[-1]), 1)
    r["mgmt_postings_yoy"] = _pct(mm.iloc[-1], mm.iloc[-13]) if len(mm) > 13 else "n/a"

    try:
        btos = targets.btos_ai_adoption()
        r["btos_adoption"] = f"{btos.groupby('date')['share'].mean().iloc[-1]:.0%}"
    except (FileNotFoundError, ValueError):
        r["btos_adoption"] = "n/a"

    try:
        ff = targets.fed_funds_rate()
        r["fed_funds"] = f"{ff['value'].iloc[-1]:.2f}%"
        r["fed_funds_yr_ago"] = f"{ff['value'].iloc[-13]:.2f}%" if len(ff) > 13 else "n/a"
    except FileNotFoundError:
        r["fed_funds"] = "n/a"

    oews = targets.oews_anchors().set_index("OCC_CODE")
    for soc, key in [("15-1255", "oews_designers"), ("11-3021", "oews_it_managers")]:
        if soc in oews.index:
            row = oews.loc[soc]
            r[key] = f"{row['TOT_EMP']:,.0f} employed, median ${row['A_MEDIAN']:,.0f}"

    if SUMMARY.exists():
        s = json.loads(SUMMARY.read_text())["robust"]
        r["sim_junior_2035_range"] = [round(v, 2) for v in s["junior_end_ratio_range"]]
        r["sim_total_2035_range"] = [round(v, 2) for v in s["total_end_ratio_range"]]
        if "managers_end_ratio_range" in s:
            r["sim_manager_2035_range"] = [round(v, 2) for v in s["managers_end_ratio_range"]]
    return r


def render(r: dict, prev: dict | None) -> str:
    def delta(key) -> str:
        if not prev or key not in prev or prev[key] in (None, "n/a"):
            return ""
        if prev[key] == r[key]:
            return " (unchanged)"
        return f" (was {prev[key]})"

    lines = [
        f"## State of the Board — {r['date']}",
        "",
        "*Generated by `des-sim-checkin` from live public data. Quantitative*",
        "*signals only — interpretation belongs in the check-in, not the tool.*",
        "",
        "### Which-world evidence",
        f"- **Output shipped ÷ design hiring**: {r['evidence_ratio']} "
        f"({r['evidence_yoy']} y/y){delta('evidence_ratio')} — leans **{r['evidence_lean']}**",
        f"- **New tech companies**: {r['formation_per_month']:,}/mo, "
        f"{r['formation_vs_plateau']} vs 2022–24 plateau{delta('formation_per_month')}",
        "",
        "### Labor market",
        f"- **Tech layoffs**: {r['layoffs_latest_month_k']}k last month; "
        f"~{r['layoffs_trailing_12mo_k']}k trailing year{delta('layoffs_trailing_12mo_k')}",
        f"- **Design-adjacent postings**: {r['design_postings_index']} "
        f"(Feb 2020 = 100), {r['design_postings_yoy']} y/y{delta('design_postings_index')}",
        "",
        "### Manager watch (middle-management compression)",
        f"- **Management postings (Indeed, all management)**: {r['mgmt_postings_index']} "
        f"(Feb 2020 = 100), {r['mgmt_postings_yoy']} y/y{delta('mgmt_postings_index')}",
    ]
    if "oews_it_managers" in r:
        lines.append(f"- **IT managers (OEWS, annual)**: {r['oews_it_managers']}{delta('oews_it_managers')}")
    if "sim_manager_2035_range" in r:
        lo_m, hi_m = r["sim_manager_2035_range"]
        lines.append(
            f"- **Simulated manager seats, 2035 vs no-AI**: {lo_m}x–{hi_m}x across all runs "
            "(span-of-control flattening with AI adoption)"
        )
    lines += [
        "",
        "### Context",
        f"- Firms using AI (BTOS, national): {r['btos_adoption']}{delta('btos_adoption')}",
        f"- **Fed funds rate (regime watch)**: {r.get('fed_funds', 'n/a')} "
        f"(year ago: {r.get('fed_funds_yr_ago', 'n/a')}){delta('fed_funds')} — "
        "appetite for design tracks capital conditions; a tightening turn is "
        "red-world pressure regardless of AI news",
    ]
    if "oews_designers" in r:
        lines.append(f"- Web/digital interface designers (OEWS): {r['oews_designers']}")
    if "sim_junior_2035_range" in r:
        lines.append(
            f"- Simulation ranges (2035 vs no-AI): junior {r['sim_junior_2035_range'][0]}x–"
            f"{r['sim_junior_2035_range'][1]}x, total {r['sim_total_2035_range'][0]}x–"
            f"{r['sim_total_2035_range'][1]}x — assumption-grid spans, not probabilities"
        )
    lines += [
        "",
        "*Caveats travel with sources: layoff totals undercount (~1/3 of events*",
        "*lack headcounts); formation = filings, not employer firms; management*",
        "*postings are all-management, not design management; app-release output*",
        "*proxy absorbs platform policy shocks. Direction over level, always.*",
    ]
    return "\n".join(lines)


def main() -> int:
    CHECKIN_DIR.mkdir(parents=True, exist_ok=True)
    readings = gather()
    prior_files = sorted(CHECKIN_DIR.glob("brief-*.json"))
    prev = json.loads(prior_files[-1].read_text()) if prior_files else None
    brief = render(readings, prev)

    stamp = dt.date.today().strftime("%Y-%m")
    (CHECKIN_DIR / f"brief-{stamp}.md").write_text(brief + "\n")
    (CHECKIN_DIR / f"brief-{stamp}.json").write_text(json.dumps(readings, indent=2) + "\n")
    print(brief)
    print(f"\n[saved to {CHECKIN_DIR}/brief-{stamp}.md — gitignored, paste into your check-in]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
